baseURL: https://go-qkbell.github.io/
title: qkbell's Devlog
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-5X49F2YSKE

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: dracula
    tabWidth: 4

params:
  env: production
  title: qkbell
  description: "qkbell's Devlog."
  keywords: [Blog, Portfolio, Devlog]
  author: qkbell

  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    favicon: "/icons/gopher.png"
    favicon16x16: "/icons/gopher.png"
    favicon32x32: "/icons/gopher.png"

  label:
    icon: "/icons/gopher.png"

  homeInfoParams:
    Title: "Hello, 世界"
    Content: >
      [![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgo-qkbell.github.io&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false)](https://hits.seeyoufarm.com)<br>
      Welcome to my Devlog.<br>
      I'm a Go Programmer.<br>
      I will be posting in Korean and English.<br>
      I'm not a fluent English writer, but I will try my best. &#128512;

  socialIcons:
    - name: github
      url: "https://github.com/go-qkbell"
    - name: email
      url: "mailto:go.qkbell@gmail.com"

  # Analytics
  analytics:
    google:
      SiteVerificationTag: "NBo4TsbNrXb16QhU1PVuOIkFzrrGtXCuY393ocMu4yI"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Archive
      url: /archives
    - name: Categories
      url: /categories
    - name: Search
      url: /search

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 1.0